---
# tasks file for ansible-role-uchiwa

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- include: "configure-{{ ansible_os_family }}.yml"

- name: Create uchiwa_log_dir
  file:
    path: "{{ uchiwa_log_dir }}"
    owner: "{{ uchiwa_user }}"
    group: "{{ uchiwa_group }}"
    state: directory

- name: Create uchiwa_config_fragments_dir
  file:
    path: "{{ uchiwa_config_fragments_dir }}"
    owner: "{{ uchiwa_user }}"
    group: "{{ uchiwa_group }}"
    state: directory

- name: Create log directory
  file:
    path: "{{ uchiwa_log_dir }}"
    mode: 0755
    owner: "{{ uchiwa_user }}"
    group: "{{ uchiwa_group }}"
    state: directory
  notify: Restart uchiwa

- name: Create uchiwa_conf_file
  template:
    src: uchiwa.json.j2
    dest: "{{ uchiwa_conf_file }}"
    validate: "python -c 'import sys; import json; json.loads(open(sys.argv[1]).read())' %s"
  notify: Restart uchiwa

- name: Start uchiwa
  service:
    name: "{{ uchiwa_service }}"
    enabled: true
    state: started
